### PR TITLE
Fix running through Linux shortcut

### LINKED ISSUE #340: Having problem on launching
I'm using the appimage on linux mint. I added the shortcut on my menu but when launching it from there an error pos up. It's launching normely if I Double click on the Appimage file but I want it to launc from the menu for daily use.
Screenshot_20201010_155754 Though I'm not sure if it's a bug or what but an issue for me.
Thank U so much for making Tahoma and I wish you can help me with my problem

### PR DESCRIPTION
**Pull request by manongjohn**
This PR fixes #340 

For Linux systems, when launching from a shortcut (symbolic link), the working directory is where the application was started from so Tahoma2D cannot find the tahomastuff directory.

Added logic for Linux systems only, to attempt to convert a symbolic link to the true path of the application and set the working directory to that.

### CODE REVIEW

**Comment by manongjohn** [comment]
Just realized I need to fix the ffmpeg detection

**Comment by jeremybullock** [comment]
thanks for the quick fix.

**Comment by manongjohn** [comment]
This should be good to go now.

**Comment by jeremybullock** [comment]
Awesome.  Thanks,

**Pull request merged**
