### PR TITLE
Remove creation and use of room_menubar.xml

### PR DESCRIPTION
**Pull request by manongjohn**
This PR removes the creation and use of room_menubar.ini files. It primarily impacts Windows users.

Issue:  Tahoma2D currently does not allow menu customizations, however it still creates and uses room_menubar.ini files.  Depending on how a user upgrades to a newer version, this becomes a problem because the room_menubar.ini files are not updated and will hide any menu changes we've made.  Users would need to reset rooms in order to get the changes which also has the bad side effect of resetting the room layouts and deleting custom rooms.

### CODE REVIEW

**Comment by jeremybullock** [comment]
Awesome!

**Comment by jeremybullock** [comment]
I'd actually be fine with losing the whole feature instead of ifdef'ing it out.  I don't see bringing it back.

**Comment by jeremybullock** [comment]
Should this go into 1.1?

**Comment by artisteacher** [comment]
Yes! Should it have any impact on #184?

**Comment by manongjohn** [comment]
@jeremybullock I honestly can't imaging us bringing it back either.  I was half tempted to remove everything related to it. Would take me a bit to do.

@artisteacher I just tested it and no, it does not fix that unfortunately.  I think what is happening is when it deletes the room, it blindly deletes the menubar. For macOS, these should only be 1 so it's deleting it.

Surprisingly, despite my change, this doesn't happen on Windows and I would expect it to since it's supposed to be just 1 menubar now. This is prompting me to look a little more into how the menubar is being handled.  I'll try and fix it with this PR.

**Comment by manongjohn** [comment]
I've removed the logic that managed 1 menubar per room, even though they were the same. I've also removed related to customizing them.  Now there is only 1 menubar for the entire application. 

This change will fix #184.

**Comment by jeremybullock** [comment]
Awesome work.  LGTM.

**Pull request merged**
