### PR TITLE
Attempt at fixing mac record audio crash. . .

### LINKED ISSUE #158: Record audio crash
**Describe the bug**
Clicking on the record button on the "Record Audio" window causes a crash

**To Reproduce**
List steps to reproduce the behavior.
1. Open the "Record Audio" window
2. Click record

**Expected behavior**
Audio to record without a crash.

**Crash Report**
[record_audio.txt](https://github.com/turtletooth/tahoma/files/5208925/record_audio.txt)

**Device Information:**
 - OS: macOS 10.15.6 & 10.14.6
 - Tahoma Version: 1.0.1

### PR DESCRIPTION
**Pull request by jeremybullock**
closes #158 hopefully

This should ask for permission before accessing the mic.
It is probably missing some #include directives.

I can't test it, but hopefully this is the start of getting things working.

@artisteacher When you get the chance, could you take a look?  My guess is that it will throw missing include errors.  But I don't know what to include yet.

### CODE REVIEW

**Comment by artisteacher** [comment]
Thanks for tackling this again. There are 12 errors, so the build fails. Normally, there are just 3 when it passes.
Screen Shot 2020-10-18 at 10 02 32 PM
Screen Shot 2020-10-18 at 10 01 53 PM

From what I've read, I think that avfoundation needs to be included.

**Comment by jeremybullock** [comment]
Push another version.

**Comment by artisteacher** [comment]
The build gets to 90% & then there are too many errors.
[microphone_errors.txt](https://github.com/turtletooth/tahoma2d/files/5398878/microphone_errors.txt)
Screen Shot 2020-10-18 at 11 22 30 PM

**Comment by jeremybullock** [comment]
K.  Thanks for trying.  I don't know what else to try on my side.

**Comment by artisteacher** [comment]
From a google search, it looks like those errors come from having some code in objc instead of c++

**Pull request closed without merging**
